In [32]:
import numpy as np

In [34]:
l = [1,2,3,4,5,6,7,8,9]

In [36]:
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [44]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
l = np.arange(0,10)

In [50]:
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [54]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [62]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [64]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [69]:
np.eye(5,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [75]:
np.linspace(0,4,10)

array([ 0.        ,  0.44444444,  0.88888889,  1.33333333,  1.77777778,
        2.22222222,  2.66666667,  3.11111111,  3.55555556,  4.        ])

In [78]:
np.random.rand(10,2)

array([[ 0.86378274,  0.39001635],
       [ 0.96673084,  0.93311209],
       [ 0.44632592,  0.08787363],
       [ 0.62059863,  0.09692693],
       [ 0.48174688,  0.22874841],
       [ 0.63171682,  0.55811569],
       [ 0.68347892,  0.59675772],
       [ 0.25241793,  0.7213272 ],
       [ 0.17945608,  0.14367962],
       [ 0.81653562,  0.5829985 ]])

In [81]:
np.random.randn(3,5)

array([[ 0.6833803 , -0.24971075, -0.59872123,  0.43075378, -0.18230086],
       [-0.56085427, -0.83675924, -0.29194607,  0.29156831, -1.11816216],
       [-0.08991829, -0.43484457,  0.75231643,  0.78594693, -0.78690207]])

In [84]:
np.random.randint(0,10,20)

array([9, 6, 3, 1, 5, 0, 5, 0, 2, 5, 0, 4, 4, 7, 4, 0, 1, 5, 2, 9])

In [85]:
arr = np.arange(25)

In [89]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
arr = np.random.randint(0,10,9)

In [92]:
arr

array([6, 4, 8, 3, 8, 1, 7, 1, 6, 0])

In [93]:
arr.max()

8

In [94]:
arr.min()

0

In [95]:
arr.argmin()

9

In [96]:
arr.argmax()

2

In [101]:
arr.shape

(9,)

In [103]:
arr.reshape(3,3)

array([[8, 9, 1],
       [2, 0, 4],
       [0, 8, 9]])

In [106]:
arr.dtype

dtype('int32')

In [108]:
arr = np.arange(0,11)

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr[-1 : -1]

array([], dtype=int32)

In [116]:
arr[:] = 10

In [117]:
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [118]:
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [119]:
slice_arr = arr

In [120]:
slice_arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [121]:
slice_arr[:] = 0

In [122]:
slice_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [123]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [124]:
slice_arr = arr.copy()

In [125]:
slice_arr
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [126]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [127]:
slice_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
slice_arr[: ] = 200

In [129]:
slice_arr

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [130]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
arr = np.arange(0,11)

In [132]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [133]:
bool_array = arr > 5

In [134]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [136]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [138]:
arr = np.arange(11)

In [140]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [142]:
arr / arr

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [143]:
arr / 0

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf])