#                                # Numpy Tutorials

# 

##                                             1-  Basics

In [29]:
my_list = [1, 2, 3]

In [30]:
import numpy as np

In [31]:
arr = np.array(my_list)

In [32]:
arr

array([1, 2, 3])

In [33]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [35]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### arange ([start,] stop[, step,], dtype=None)  Return evenly spaced values within a given interval

In [36]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

####  zeros and one. np.ones(shape, dtype=None, order='C')   Return a new array of given shape and type, filled with ones.

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.ones((2,2), dtype= int)

array([[1, 1],
       [1, 1]])

#### linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None) Return evenly spaced numbers over a specified interval.

In [40]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Identity matrix - np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C') Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [44]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### random

In [46]:
#rand(d0, d1, ..., dn). Random values in a given shape.
np.random.rand()

0.36798663286286626

In [51]:
# randn(d0, d1, ..., dn). Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(2,3)

array([[ 1.8161822 , -2.23456606, -0.07082094],
       [-0.28749808,  1.11851488,  1.0202556 ]])

In [54]:
# randint(low, high=None, size=None, dtype='l'). Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(0, 10, 2)

array([9, 4])

#### Reshape np.reshape(a, newshape, order='C'). Gives a new shape to an array without changing its data.

In [64]:
np.reshape(np.arange(9), (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### max, min, indexof (max, min) of random array.

In [66]:
random_arr = np.random.randint(0, 100, 10)
random_arr

array([68, 56, 78, 87,  2, 68, 64, 90,  8, 28])

In [69]:
print('max', random_arr.max())
print('min', random_arr.min())
print('index of max', random_arr.argmax())
print('index of min ', random_arr.argmin())

max 90
min 2
index of max 7
index of min  4


#### shape of an array. Return (row, col). 

In [71]:
random_arr.shape

(10,)

#### To check data type of an array

In [73]:
random_arr.dtype

dtype('int32')

# 

##                                         2 - Indexing And Selection

#### Indexing

In [94]:
arr = np.arange(11)

In [76]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [78]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [80]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr[0:5] = 100

In [83]:
slice_of_arr = arr[:5]

In [84]:
# it will reflect to original arr as well.
slice_of_arr[:] = 99

In [85]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [86]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [88]:
r_copy = arr.copy()

In [89]:
r_copy[:] = 100

In [91]:
r_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [92]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [106]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [100]:
arr_2d[0]

array([ 5, 10, 15])

In [101]:
arr_2d[1][1]

25

In [104]:
arr_2d[1,2]

30

In [107]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [111]:
arr_2d[1:3,1:3 ]

array([[25, 30],
       [40, 45]])

In [112]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [113]:
arr = np.arange(1, 10)

In [117]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
#Convert into boolean array.
bool_arr = arr > 5

In [115]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [116]:
#Take only those values which are True
arr[bool_arr]

array([6, 7, 8, 9])

In [118]:
# do above in one step
arr[arr > 5]

array([6, 7, 8, 9])

In [119]:
arr[arr < 3]

array([1, 2])

In [121]:
arr_2d = np.arange(50).reshape(5,10)

In [122]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

##                                                    3-  Numpy Operations

In [123]:
arr = np.arange(11)

In [124]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [125]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [126]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [127]:
arr*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [128]:
arr/0

D:\Program Files (x86)\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Program Files (x86)\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [129]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [130]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [131]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [132]:
np.max(arr)

10

In [133]:
np.min(arr)

0

In [134]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [135]:
np.log(arr)

D:\Program Files (x86)\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])